apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

patches:
  - path: env-patch.yaml

images:
  - name: matteotv/argocd-demo
    newTag: dev-20260724-5
