apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-argocd
  labels:
    app: demo-argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-argocd
  template:
    metadata:
      labels:
        app: demo-argocd
    spec:
      containers:
        - name: demo-argocd
          image: matteotv/argocd-demo
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: "base"
            - name: VERSION
              value: "placeholder"
            - name: BG_COLOR
              value: "#333333"
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
